@SocialMediaAPI_HostAddress = https://localhost:7245
@token = CfDJ8C8gBUuK-b5MnLDc6zYJyQ4wHLjZuRH_kXEb6xxZ34sxpBWRjIgSYVqpUF793hvtC27Z4xnSJpPLImBtsqRqY8BHSqfVPERyVBjNGPfeodh74Ru9LSJna5okz2Xffmbrf_u-TebDoT8Scvxy6wN_qlp050_80B6P2-482TMNB0Fu8qOeXYcyM0RGNFa9bbFNH2_WK8G5mUk30YtckTrXNKfxqyaZSi1MM2f5qJrSysB9OzuqtLPbn2YAIBakqgJ8wy7dSDpqB0ksKd9UOEWrmUTFF8bxhvWMDg0rp73k2W9nMKtFrPa5i5WBPAa1HVuePXv1z_9oFILHHzJQpcquPFXUVzZnH84oJchfG1pdyneJnparRp0ANOv_p1rWO6gowqBY6OcreSijxWCFDciM0M_8rEiTFH-2MCAF5DO5Bfvio3NCFq-ZNVgtXCQ4qhWIlfh4A96taX0pTCguqB3xKco9rbw8U6I3k9tmuPiDQBen8W8SZOrZ2wWP4DYA_V9Fz7pzvpq51iEtmResmOE75d-OXHbeI3iPEzWoveAfKA2oxlp3iwEEeSiJ764iWyBSAJomFXGW-jugL4qyXg0r_SB60Arq_vCSHC-U_0Bg85bT8_t7E8c_c2oqAS6jg3DkgGt5IFl4XsrGM4OTPBdnhFRaMpL3Zox1UYIPqZ6Te6JuGzcQsG9OMzviLz9_bXZAdY1d-8SBuAqR8CqSHLlNPbHf7WAR79iu8RIqK2Y8Cxd3zlXOJbB5xXjj83mubyJHxg

Post {{SocialMediaAPI_HostAddress}}/api/users/register
Content-Type: application/json
{ 
  "FullName": "Kero Nabil",
  "Username": "kero",
  "email": "kero@kero",
  "password": "Password1!"
}
###

Post {{SocialMediaAPI_HostAddress}}/api/users/login
Content-Type: application/json
{
  "email": "k",
  "password": "Password1!"
}
###

POST {{SocialMediaAPI_HostAddress}}/api/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Title": "...$..",
  "Description": "kero description",
  "Images" : [
    "image1",
    "image2"
  ]
}
###

GET {{SocialMediaAPI_HostAddress}}/api/posts/58
Authorization: Bearer {{token}}
###


DELETE {{SocialMediaAPI_HostAddress}}/api/posts/54
Authorization: Bearer {{token}}
###

PUT {{SocialMediaAPI_HostAddress}}/api/posts/58
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "title" : "new....",
  "description" : "....",
  "Images" : [
    "image1",
    "image2"
  ]
}
###

GET {{SocialMediaAPI_HostAddress}}/api/posts
Authorization: Bearer {{token}}
###

GET {{SocialMediaAPI_HostAddress}}/api/posts/feed
Authorization: Bearer {{token}}
###

POST {{SocialMediaAPI_HostAddress}}/api/users/de594ce8-40f8-45d2-b04a-636338a59b18/follow
Authorization: Bearer {{token}}
###

DELETE {{SocialMediaAPI_HostAddress}}/api/users/f74769bf-176d-443e-92f8-f9f998942172/unfollow
Authorization: Bearer {{token}}
###

GET {{SocialMediaAPI_HostAddress}}/api/users/e8eb0fc9-ffd4-43c6-a266-ba5d59d5b6a9/followers
Authorization: Bearer {{token}}
###

GET {{SocialMediaAPI_HostAddress}}/api/users/e8eb0fc9-ffd4-43c6-a266-ba5d59d5b6a9/following
Authorization: Bearer {{token}}
###

GET {{SocialMediaAPI_HostAddress}}/api/users/e8eb0fc9-ffd4-43c6-a266-ba5d59d5b6a9
Authorization: Bearer {{token}}
###

PATCH {{SocialMediaAPI_HostAddress}}/api/users/me
Authorization: Bearer {{token}}
Content-Type: application/json
{
  "Bio": ""
}
###

POST {{SocialMediaAPI_HostAddress}}/api/posts/71/like
Authorization: Bearer {{token}}
###

GET {{SocialMediaAPI_HostAddress}}/api/posts/58/likes
Authorization: Bearer {{token}}
###

POST {{SocialMediaAPI_HostAddress}}/api/posts/70/comments
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Content" : "This is a comment 6"
}

###

GET {{SocialMediaAPI_HostAddress}}/api/posts/58/comments/13
Authorization: Bearer {{token}}
###

PATCH {{SocialMediaAPI_HostAddress}}/api/posts/53/comments/2
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Content": "This is a new comment"
}
###

POST {{SocialMediaAPI_HostAddress}}/api/posts/70/comments/19/like
Authorization: Bearer {{token}}
###

GET {{SocialMediaAPI_HostAddress}}/api/posts/53/comments/2/likes
Authorization: Bearer {{token}}
###

DELETE {{SocialMediaAPI_HostAddress}}/api/posts/53/comments/6
Authorization: Bearer {{token}}
###

DELETE {{SocialMediaAPI_HostAddress}}/api/users/me
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Password": "Password1!"
}
###

GET {{SocialMediaAPI_HostAddress}}/api/search/posts
Authorization: Bearer {{token}}
###

GET {{SocialMediaAPI_HostAddress}}/api/search/users?SearchPhase=oN
Authorization: Bearer {{token}}
###

POST {{SocialMediaAPI_HostAddress}}/api/admin/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "UserId" : "de594ce8-40f8-45d2-b04a-636338a59b18",
  "RoleName" : "User"
}
###

DELETE {{SocialMediaAPI_HostAddress}}/api/admin/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "UserId" : "de594ce8-40f8-45d2-b04a-636338a59b18",
  "RoleName" : "User"
}
###

GET {{SocialMediaAPI_HostAddress}}/api/admin/users?PageSize=10
Authorization: Bearer {{token}}
###

DELETE {{SocialMediaAPI_HostAddress}}/api/admin/users/de594ce8-40f8-45d2-b04a-636338a59b18
Authorization: Bearer {{token}}

###

DELETE {{SocialMediaAPI_HostAddress}}/api/admin/posts/70
Authorization: Bearer {{token}}

###

DELETE {{SocialMediaAPI_HostAddress}}/api/admin/posts/71/comments/19
Authorization: Bearer {{token}}

###
