@SocialMediaAPI_HostAddress = https://localhost:7245
@token = CfDJ8C8gBUuK-b5MnLDc6zYJyQ4EgHclAvSK4THFpbYMRaL2pfqt3PyR-wumwChEseiGTv0Iy29as-fNsQHsk3PsPsuzOoL3p5QPBW2c2wMIawy8T0wd3f8kHrKmzlZ-59pDaETfR3z37lqFRy6t_yun8mQndM4YFfe1Az_ej-fNEpjdOrJ-r-2TqClT7s6_bZvosV4qAdHWiP4q5lcB6XJqx0eZnhh0Jckvuqbb5gseJwlv9RFuFL5e7xZGSoHv4TLWg0mgbzfT-jjazyEgqNWcpuV943bokwC4_2Hrun51OXQGubl9DVhnVSkzTyEQ3ZbS3YPuWnpCtD9anbWzbYHbGQzTECXKaj54mosi7gX3BeEzE_bbLNxO034k-GkSywRl67Ox3_Y-naGePEOZjqIGHwpLF5ly6Gj4gsx2qd2l8eZWa4qUtT3R4Cp95gP61MAlrfaBxcGBFA50ua1ws1DBPojv32lG65sCNoUS2yFerxcaAdD1XbQZd9sfWmas7fDTQ0Iah8WGeVYo4wKDsdlAyIppTYc_n24EqCd8h2zCXLDeEaJDsyAjhIYQnAaUOj0RT_1ouJkoXfRh_DBgF22QiY3gBO-YcZ354CdQ6TGl0O70ooPTJ1KxC5uicT_suCZeHw9SPifvmNwPYZJ_H_oaaNNOnnGJ_wgcS1KxVc2a8tH2

Post {{SocialMediaAPI_HostAddress}}/api/users/register
Content-Type: application/json
{ 
  "FullName": "Kero Nabil",
  "Username": "KeroNabil",
  "email": "kero@kero",
  "password": "Password1!"
}
###

Post {{SocialMediaAPI_HostAddress}}/api/users/login
Content-Type: application/json
{
  "email": "kero",
  "password": "Password1!"
}
###

POST {{SocialMediaAPI_HostAddress}}/api/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Title": ".....",
  "Description": "kero description"
}
###

GET {{SocialMediaAPI_HostAddress}}/api/posts/33
Authorization: Bearer {{token}}
###


DELETE {{SocialMediaAPI_HostAddress}}/api/posts/29
Authorization: Bearer {{token}}
###

PUT {{SocialMediaAPI_HostAddress}}/api/posts/33
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "title" : "new....",
  "description" : "....",
  "Images" : [
    "image1",
    "image2"
  ]
}
###

GET {{SocialMediaAPI_HostAddress}}/api/posts?pageNumber=2&searchPhase=
Authorization: Bearer {{token}}
###

POST {{SocialMediaAPI_HostAddress}}/api/users/f74769bf-176d-443e-92f8-f9f998942172/follow
Authorization: Bearer {{token}}
###
