@SocialMediaAPI_HostAddress = https://localhost:7245
@token = CfDJ8C8gBUuK-b5MnLDc6zYJyQ4GuCSBrM6czLcq4t8zAewfeSndk4u4j7Pz2W0-JuUQTB1UJPo79iWBIskaxzfH7_kH-UFGhqVVWCF-vAvJ32xsza1GYl4FtiOPm-pJOu6R5cMyi9_Tc8KP6q20TLHN15FWi7bMyuS_GJYWeoYayJSORaUTw8gFuiDs3iI7Mt3cCNqC3wviHr3paOoX7Gmb5aIIHP4yIco3b_pgSC-nKDtGatwlTHzdov-aFNh_Ifbbr0uyM8kJK2RnGpSxJxBNxCugisxksyaZQfrz_Wmn_SYelpVRmRZi9TOWD2R_55F50abVeBgkvH9IXC7ybSVT1bJR2-kwMYd3C5pi9oujpmejdn_B_9DfgQK7iVrQ06Igckx37HyNA9fUfR3eVufwegeTskPhXgYMd3spmIApRWjSuIpU-_DRHUAoJx4wHY-kHiynz37M-mYKf2xiXoeWILA_RHDysAvxSJOvb611XGgqTYgJz_nX21EjlHkB2KxlQnq6qBwdqP3boBHIvSTSWZhdoCfqokMCWtGz6KurKsFNqTrT5X8PpMQpluuL9o_86YNTgRN2bzIgBkHRcMVldsBRBs75L7sLjVRua4fzUH5VN3aqkR4Ui87oyV3r_K3Pl-JlySZbg_HS4Z18W7LL0DOmVmGfzbq38r9aQqVQ40yo

Post {{SocialMediaAPI_HostAddress}}/api/users/register
Content-Type: application/json
{
  "email": "k@k.com",
  "password": "Password1!"
}

###
Post {{SocialMediaAPI_HostAddress}}/api/users/login
Content-Type: application/json
{
  "email": "k@k.com",
  "password": "Password1!"
}

###

POST {{SocialMediaAPI_HostAddress}}/api/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Title": "post title",
  "Description": "post description",
  "Images" : [
    "image1",
    "image2",
    "image3"
  ]
}

###
